services:
  web:
    image: nginx:stable
    restart: always
    ports:
      - 20001:80
      - 4343:443
    volumes:
      - ./default.conf.template:/etc/nginx/templates/default.conf.template
      - static_volume:/usr/share/nginx/html
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - backend_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: >
      bash -c "python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py migrate data --database=hilda_data &&
               python manage.py createsuperbossgroup &&
               python manage.py import_cp_data &&
               python manage.py import_oc_data &&
               python manage.py collectstatic --no-input &&
               gunicorn hildaApp.wsgi:application --bind 0.0.0.0:8000"
    environment:
      NAME: ${NAME}
      USER: ${USER}
      PASSWORD: ${PASSWORD}
      HOST: ${HOST}
      PORT: ${PORT}
    volumes:
      - .:/app
      - static_volume:/usr/share/nginx/html
    extra_hosts:
      - ${HOST}:${HOST_IP}
    networks:
      - backend_network

networks:
  backend_network:
    external: true

volumes:
  static_volume:
