# Generated by Django 4.1.7 on 2023-03-29 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CapacitacionPrevia',
            new_name='Capacitacion',
        ),
        migrations.RemoveField(
            model_name='habilidad',
            name='carpeta_capacitacion',
        ),
        migrations.RemoveField(
            model_name='habilidadpersonalizada',
            name='habilidad',
        ),
        migrations.AlterModelOptions(
            name='capacitacion',
            options={'verbose_name_plural': 'Capacitaciones'},
        ),
        migrations.RemoveField(
            model_name='capacitacioncliente',
            name='capacitacion_en_curso',
        ),
        migrations.AddField(
            model_name='capacitacioncliente',
            name='capacitacion',
            field=models.ManyToManyField(blank=True, null=True, related_name='capacitacionesencurso', to='data.capacitacion'),
        ),
        migrations.DeleteModel(
            name='CapacitacionEnCurso',
        ),
        migrations.DeleteModel(
            name='Habilidad',
        ),
        migrations.DeleteModel(
            name='HabilidadPersonalizada',
        ),
    ]
