# Generated by Django 4.1.7 on 2023-10-08 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='curp',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='rfc',
        ),
        migrations.AddField(
            model_name='curp',
            name='personal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='data.personal'),
        ),
        migrations.AddField(
            model_name='rfc',
            name='personal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='data.personal'),
        ),
    ]
