# Generated by Django 4.1.7 on 2023-09-06 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpetaclientecontactos',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='carpetaclientegenerales',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='carpetaclientepagos',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='cliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='carpeta_cliente_contactos',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.carpetaclientecontactos'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='carpeta_cliente_generales',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.carpetaclientegenerales'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='carpeta_cliente_pagos',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.carpetaclientepagos'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.sede'),
        ),
    ]
