# Generated by Django 4.1.7 on 2023-03-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_rename_capacitacionprevia_capacitacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitacioncliente',
            name='capacitacion',
            field=models.ManyToManyField(blank=True, related_name='capacitacionesencurso', to='data.capacitacion'),
        ),
    ]
