# Generated by Django 4.1.7 on 2023-10-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_personal_curp_remove_personal_rfc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curp',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curp',
            name='sexo',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'MUJER'), (2, 'HOMBRE'), (3, 'NO BINARIO')], null=True),
        ),
    ]
