# Generated by Django 4.1.7 on 2023-10-08 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_curp_fecha_nacimiento_alter_curp_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpetaclientegenerales',
            name='domicilio',
        ),
        migrations.RemoveField(
            model_name='carpetaclientepagos',
            name='domicilio',
        ),
        migrations.RemoveField(
            model_name='carpetaempleoanterior',
            name='domicilio',
        ),
        migrations.RemoveField(
            model_name='carpetaempleoanteriorseguridadpublica',
            name='domicilio',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='domicilio',
        ),
        migrations.RemoveField(
            model_name='referencia',
            name='domicilio',
        ),
        migrations.AddField(
            model_name='domicilio',
            name='carpeta_caliente_generales',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.carpetaclientegenerales'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='carpeta_cliente_pagos',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.carpetaclientepagos'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='carpeta_empleo_anterior',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.carpetaempleoanterior'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='carpeta_empleo_anterior_sp',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.carpetaempleoanteriorseguridadpublica'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='personal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.personal'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='referencia',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.referencia'),
        ),
    ]
