# Generated by Django 4.1.7 on 2023-10-08 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_remove_carpetaclientegenerales_domicilio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domicilio',
            name='carpeta_empleo_anterior',
        ),
        migrations.RemoveField(
            model_name='domicilio',
            name='carpeta_empleo_anterior_sp',
        ),
        migrations.AddField(
            model_name='domicilio',
            name='empleo_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.empleoanterior'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='empleo_anterior_sp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.empleoanteriorseguridadpublica'),
        ),
    ]
