# Generated by Django 4.1.7 on 2023-10-09 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_alter_curp_curp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carpetaempleoanteriorseguridadpublica',
            options={'verbose_name_plural': 'Carpeta Empleos Anteriores Seguridad Publica'},
        ),
        migrations.AlterModelOptions(
            name='empleoanteriorseguridadpublica',
            options={'verbose_name_plural': 'Empleos Anteriores Seguridad Publica'},
        ),
        migrations.RenameField(
            model_name='domicilio',
            old_name='carpeta_caliente_generales',
            new_name='carpeta_cliente_generales',
        ),
    ]
