# Generated by Django 4.1.7 on 2023-10-09 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_carpetaempleoanteriorseguridadpublica_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='evaluador',
        ),
        migrations.AddField(
            model_name='evaluador',
            name='personal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='data.personal'),
        ),
    ]
