# Generated by Django 4.1.7 on 2023-10-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_remove_personal_evaluador_evaluador_personal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curp',
            name='estatus_curp',
            field=models.CharField(blank=True, choices=[('AN', 'ALTA NORMAL'), ('AH', 'ALTA CON HOMONIMIA'), ('RCC', 'REGISTRO DE CAMBIO AFECTANDO A CURP'), ('RCN', 'REGISTRO DE CAMBIO NO AFECTANDO A CURP'), ('BD', 'BAJA POR DEFUNCIÓN'), ('BSU', 'BAJA SIN USO'), ('BJD', 'BAJA JUDICIAL'), ('BDM', 'BAJA ADMINISTRATIVA'), ('BAP', 'BAJA POR DOCUMENTO APÓCRIFO'), ('BDP', 'BAJA POR ADOPCIÓN')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='curp',
            name='validacion_renapo',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'SI'), (2, 'NO'), (3, 'DESCONOCIDO')], null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='origen',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'PRESENCIAL'), (2, 'REMOTO')], null=True),
        ),
    ]
