# Generated by Django 4.1.7 on 2023-10-10 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_alter_curp_estatus_curp_alter_curp_validacion_renapo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areacurso',
            name='carpeta_laboral',
        ),
        migrations.RemoveField(
            model_name='capacitador',
            name='carpeta_laboral',
        ),
        migrations.RemoveField(
            model_name='ocupacion',
            name='carpeta_laboral',
        ),
        migrations.RemoveField(
            model_name='puesto',
            name='carpeta_laboral',
        ),
        migrations.AddField(
            model_name='carpetalaboral',
            name='area_curso',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='data.areacurso'),
        ),
        migrations.AddField(
            model_name='carpetalaboral',
            name='capacitador',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='data.capacitador'),
        ),
        migrations.AddField(
            model_name='carpetalaboral',
            name='ocupacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='data.ocupacion'),
        ),
        migrations.AddField(
            model_name='carpetalaboral',
            name='puesto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='data.puesto'),
        ),
        migrations.AlterField(
            model_name='carpetaexamensocioeconomico',
            name='anios_residencia',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Años residencia'),
        ),
        migrations.AlterField(
            model_name='carpetaexamensocioeconomico',
            name='banos',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Baños'),
        ),
        migrations.AlterField(
            model_name='carpetagenerales',
            name='anio_inicio_escolaridad',
            field=models.DateField(blank=True, verbose_name='Año inicio escolaridad'),
        ),
        migrations.AlterField(
            model_name='carpetagenerales',
            name='anio_termino_escolaridad',
            field=models.DateField(blank=True, verbose_name='Año término escolaridad'),
        ),
        migrations.AlterField(
            model_name='carpetamediafiliacion',
            name='boca_tamanio',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'GRANDE'), (2, 'MEDIANA'), (3, 'PEQUEÑA')], verbose_name='Boca tamaño'),
        ),
        migrations.AlterField(
            model_name='carpetamediafiliacion',
            name='cejas_tamanio',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'GRUESAS'), (2, 'DELGADAS'), (3, 'CORTAS'), (4, 'LARGAS')], verbose_name='Cejas tamaño'),
        ),
        migrations.AlterField(
            model_name='carpetamediafiliacion',
            name='ojos_tamanio',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'GRANDES'), (2, 'PEQUEÑOS'), (3, 'REGULARES')], verbose_name='Ojos tamaño'),
        ),
        migrations.AlterField(
            model_name='curp',
            name='anio_registro',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Año registro'),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='carpeta_cliente_generales',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.carpetaclientegenerales'),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='carpeta_cliente_pagos',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.carpetaclientepagos'),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='empleo_anterior',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.empleoanterior'),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='empleo_anterior_sp',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.empleoanteriorseguridadpublica'),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='personal',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.personal'),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='referencia',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.referencia'),
        ),
    ]
