default_data = {
    'nombre_completo': '',
    'curp': '',
    'ocupacion': '',
    'puesto': '',
    'razon_social': '',
    'rfc': '',
    'nombre_curso': '',
    'horas_curso': '',
    'fecha_inicial_capacitacion': '',
    'fecha_final_capacitacion': '',
    'area_curso': '',
    'nombre_capacitador': '',
    'registro_capacitador': '',
    'representante_legal': '',
    'representante_trabajadores': '',
    'logotipo': None,
    'qr_code': None,
    'fecha': '',
    'nombre_completo_personal': '',
    'id_racek': '',
    'rfc_personal': '',
    'sexo': '',
    'edad': '',
    'empresa': '',
    'nombre_completo_dentista': '',
    'firma_dentista': '',
}
